/*
Deployment script for Releases

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO
:setvar DatabaseName "UnitTesting" --DATABASE OF UNIT TESTING
:setvar TestDatabaseName "TutorialsSqlServerUnitTestCiCd" --DATABASE OF TESTING

:setvar UserName "sa" --Parameter is null if the server use windows authentication
:setvar UserPassword "jelszo" --Parameter is null if the server use windows authentication


GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END
GO

USE [$(DatabaseName)];
GO

DECLARE @databaseName VARCHAR(256) = '$(TestDatabaseName)';
DECLARE @testsFilePath VARCHAR(2000) = 'C:\development\source\repos\TutorialsSqlServerUnitTestCiCd\TestIdeDependentTutorialsSqlServerUnitTestCiCd\UnitTests\'; --PATH OF POWERSHELL SCRIPT FILE
DECLARE	@testsFileName  VARCHAR(256) = 'RunTests.ps1'; --DEFAULT: RunTests.ps1
DECLARE	@userName VARCHAR(256)  = '$(UserName)'; 
DECLARE	@userPassword VARCHAR(256) = '$(UserPassword)'; 

-------------------------------------------------
--CONFIGURING TESTFRAMEWORK
-------------------------------------------------
EXEC dbo.AddTestframeworkParameters_usp @databaseName = @databaseName,
										@testsFilePath = @testsFilePath,
										@testsFileName  = @testsFileName,
										@userName  = @userName,
										@userPassword = @userPassword;

-------------------------------------------------
--REGISTER TEST DIRECTORY
-------------------------------------------------
EXEC AddTestScriptDirectory_usp @directoryName = 'CreateTestEnviroment',
								@databaseName = @databaseName;
EXEC AddTestScriptDirectory_usp @directoryName = 'DependentObjects\Objects\Sales\Programmability',
								@databaseName = @databaseName;
EXEC AddTestScriptDirectory_usp @directoryName = 'DeleteTestEnviroment',
								@databaseName = @databaseName;
